### ISSUE TITLE
Publish this plugin to npm

### ISSUE THREAD

**Issue by abdulkareemnalband** [heroboy/generate-typescript-switch-case-for-enum-type-language-service-plugin#1]
## usecase
to use this plugin in any other editor which implements typescript lsp

Publish this plugin to npm.
`tsconfig.json` provides `compilerOptions.plugins` key where we can set this plugin and it will work without installing extension

**Comment by heroboy** [comment]
Already
https://www.npmjs.com/package/generate-typescript-switch-case-for-enum-type-language-service-plugin

**Comment by abdulkareemnalband** [comment]
Thanks last time i could find it
